language: c

arch:
  - amd64
  - arm64-graviton2
virt: lxd
group: edge

script: 
  - cd build && cmake ../ && make
  - ./tars2node
  
#before_install：install 阶段之前执行
#before_script：script 阶段之前执行
#after_failure：script 阶段失败时执行
#after_success：script 阶段成功时执行
#before_deploy：deploy 步骤之前执行
#after_deploy：deploy 步骤之后执行
#after_script：script 阶段之后执行

